#!/bin/bash

mkdir folder
getinput "archive" > archive.tar.gz
tar zxvf archive.tar.gz -C folder
if [ $? -ne 0 ]
then
	feedback-result failed
	feedback-msg -m "The decompression of your archive failed, did you give the right arguments to tar(1)?"
else
	ls folder -R > file2.txt
	diff -q file.txt file2.txt
	if [ $? -ne 0 ]
    then
		feedback-result failed
		feedback-msg -m "The decompressed archive does not correspond with the original"
	else
		feedback-result success
        	feedback-msg -m "Fine"
	fi
fi
