#!/bin/bash

export CFLAGS="-I./adds"
export LDFLAGS="-L./adds"

size_array=$(getinput q3)
if [ "$size_array" == "20" ]; then
    feedback --result success
elif [ "$size_array" == "8" ]; then
    feedback --result failed --feedback "Question 3 : Un tableau n’est pas juste un pointeur."
    exit 1
else
    feedback --result failed --feedback "Erreur à la question 3"
    exit 1
fi

size_pointer=$(getinput q5)
if [ "$size_pointer" == "8" ]; then
    feedback --result success
else
    feedback --result failed --feedback "Erreur à la question 5"
    exit 1
fi

size_array_arg=$(getinput q6)
if [ "$size_array_arg" == "8" ]; then
    feedback --result success
elif [ "$size_array_arg" == "4" ]; then
    feedback --result failed \
        --feedback "Question 6 : Le prototype de pipe équivaut en fait à \`\`int pipe(int *filedes);\`\`"
    exit 1
else
    feedback --result failed --feedback "Erreur à la question 6"
    exit 1
fi

compiler_out=$(clang -std=gnu99 -L/usr/lib64/llvm $LDFLAGS $CFLAGS -lclang check.c adds/*.c -o check 2>&1)
if [ $? -ne 0 ]; then
    feedback --result crashed --feedback "Le programme de test n’a pas pu être compilé::

$(echo "$compiler_out" | sed 's/^/    /')
"
    exit 1
fi

getinput q1 > q1.c
getinput q2 > q2.c
getinput q4 > q4.c
getinput q7 > q7.c

test_out=$(./check 2>&1)

if [ $? -eq 0 ]; then
    feedback --result success
elif [ -n "$test_out" ]; then
    feedback --result failed --feedback "Le test s’est terminé avec l’erreur suivante::

$(echo "$test_out" | sed 's/^/    /')
"
fi
