#!/bin/bash

# Get student code for `make_calc_simple` and parse it in the template
parsetemplate -o student/Makefile student/Makefile.tpl

# Get student code for `make_calc` and parse it in the template
parsetemplate -o student/Makefile2 student/Makefile2.tpl


# Try to make student code for `make_calc_simple` exercise
make

# Does file exist? If yes, check for diffs with working code
if test -e student/calc
then
    diff reference/calc student/calc
    if [ $? -ne 0 ]
    then
        feedback-result failed
        feedback-msg -m "Your Makefile is not correct."
    else
        feedback-result success
        feedback-msg -m "You made it!"
    fi
else
    feedback-result failed
    feedback-msg -m "The executable file calc was not detected."
fi

# Try to make student code for `make_calc` exercise
make make2

ls student/ -la
# Do object files exist? If yes, check for diffs with working code
if test -e student/{calc,operations}.o
then
    diff reference/{calc,operations}.o student/{calc,operations}.o
    if [ $? -ne 0 ]
    then
        feedback-result failed
        feedback-msg -m "Your Makefile is not correct."
    else
        feedback-result success
        feedback-msg -m "You made it!"
    fi
else
    feedback-result failed
    feedback-msg -m "At least on of the object files was not detected."
fi

