#!/bin/bash

# Student score
score=100

# Get student code for `make_calc_simple` and parse it in the template
parsetemplate -o student/Makefile student/Makefile.tpl

# Get student code for `make_calc` and parse it in the template
parsetemplate -o student/Makefile2 student/Makefile2.tpl


# Try to make student code for `make_calc_simple` exercise
make

# Does file exist? If yes, check for diffs with working code
if test -e student/calc
then
    diff reference/calc student/calc
    if [ $? -ne 0 ]
    then
        feedback-result -i make_calc_simple failed
        feedback-msg -i make_calc_simple -m "Your Makefile is not correct."
        feedback-result failed
        feedback-msg -m "Try again"
        ((score-=50))
    else
        feedback-result -i make_calc_simple success
        feedback-msg -i make_calc_simple -m "You made it!"
    fi
else
    feedback-result -i make_calc_simple failed
    feedback-msg -i make_calc_simple -m "The executable file calc was not detected."
    feedback-result failed
    feedback-msg -m "Try again"
    ((score-=50))
fi

# Try to make student code for `make_calc` exercise
make mrproper2
ls student/

make make2
ls student/
# Do object files exist? If yes, check for diffs with working code
if test -e student/calc.o
then
    diff reference/calc.o student/calc.o
    if [ $? -ne 0 ]
    then
        feedback-result -i make_calc failed
        feedback-msg -i make_calc -m "Your Makefile is not correct."
        feedback-result failed
        feedback-msg -m "Try again"
        ((score-=25))
    else
        feedback-result -i make_calc success
        feedback-msg -i make_calc -m "You made it!"
    fi
elif test -e student/operations.o
then
	diff reference/operations.o student/operations.o
    if [ $? -ne 0 ]
    then
        feedback-result -i make_calc failed
        feedback-msg -i make_calc -m "Your Makefile is not correct."
        feedback-result failed
        feedback-msg -m "Try again"
        ((score-=25))
    else
        feedback-result -i make_calc success
        feedback-msg -i make_calc -m "You made it!"
	fi
else
    feedback-result -i make_calc failed
    feedback-msg -i make_calc -m "At least on of the object files was not detected."
    feedback-result failed
    feedback-msg -m "Try again"
    ((score-=50))
fi

echo $score

feedback-grade $score
if [ $score -eq 100 ]
then 
	feedback-result success
else
	feedback-result failed
fi
