#! /bin/bash

usr=$(getinput @username)
last=$(echo $usr | sha256sum)

for i in {1..5}
do
	last=$(echo $last | sha256sum)
done

rep=$(getinput q1)

rep=$(echo $rep | sed 's/ .*//g')  #Ppour éviter le non match si on ne colle pas le tiret qui suit le hash
last=$(echo $last | sed 's/ .*//g')

if [ "$rep" == "$last" ]
then
	feedback-result success
else
	feedback-result failed
	feedback-msg -m "Ce n'est pas le bon code, avez-vous entré votre pseudo inginious et pas ucl ? Ce n'est pas d'office le même."
fi
