#!/bin/bash

export CFLAGS="-I./adds"
export LDFLAGS="-L./adds"

compiler_out=$(clang -std=gnu99 -L/usr/lib64/llvm $LDFLAGS $CFLAGS -lclang check.c adds/*.c -o check 2>&1)
if [ $? -ne 0 ]; then
    feedback --result crashed --feedback "Le programme de test n’a pas pu être compilé::

$(echo "$compiler_out" | sed 's/^/    /')
"
    exit 1
fi

getinput q8 > q8.c
getinput q9 > q9.c
getinput q10 > q10.c
getinput q11 > q11.c
getinput q12 > q12.c

test_out=$(./check 2>&1)

if [ $? -eq 0 ]; then
    feedback --result success
elif [ -n "$test_out" ]; then
    feedback --result failed --feedback "Le test s’est terminé avec l’erreur suivante::

$(echo "$test_out" | sed 's/^/    /')
"
fi
