#!/bin/bash

getinput length    > length.h
getinput count     > count.h
getinput push      > push.h
getinput pop       > pop.h
getinput free_list > free_list.h

CFLAGS+="-I./adds"
LDFLAGS+="-L./adds"

export CFLAGS
export LDFLAGS

./check-c-program -u list.c -t list_test.c -m memcheck.c
