#! /bin/bash

getinput "file" | sed 's/ //g' | sed ':a;N;$!ba;s/\n//g' > out2 #remove spaces and newlines
diff out2 error1
if [ $? -eq 0 ]
then
	feedback-result failed
	feedback-msg -m "Check the order of the different utilities you call"
else
	diff out2 error2
	if [ $? -eq 0 ]
	then
		feedback-result failed
		feedback-msg -m "You have to do this exercise on Linux!"
	else
		diff out out2
		if [ $? -ne 0 ]
		then
			feedback-result failed
			feedback-msg -m "The file does not contain the correct list of hashtag."
		else
			feedback-result success
			feedbach-msg -m "Fine"
		fi
	fi
fi
